### ISSUE TITLE
possible show hand command

### ISSUE THREAD

**Issue by Something-Inconspicuous** [imacrazyguy412/Poker-Bot#5]
we might need to use a command to show players their hands in order to use setEphermeral(), but idk. If there is an alternate we can do that instead.

**Comment by imacrazyguy412** [comment]
The method for sending messages can have a parameter that sets ethereal if true

**Comment by Something-Inconspicuous** [comment]
it would also need to pass the user to that method, and then the bot would need to get the actual user itself from just the tag as a string. And I don't even know if ephemeral messages even work outside of replies
